name: tests

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-go@v7
        with:
          go-version-file: go.mod

      - name: go vet
        run: go vet ./...

      - name: go test
        run: go test ./...
